### ISSUE TITLE
Hacktoberfest 2020: Fix the deadlink in README

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/Python-for-SysAdmin-Part-I#4]
# Hacktoberfest 2020: Fix the deadlink

Currently, there are a couple of deadlinks in README.md such as these in Content Table, you click these it goes nowhere and that's really bad user experience:
- - - 
![Screen Shot 2020-10-02 at 12 18 59](https://user-images.githubusercontent.com/5674762/94894618-755dd580-04a9-11eb-91b4-85cd90d117de.png)

### Acceptance Criteria:
- Create a section for each deadlink in the content table and add text for example "Coming soon" or something, such that users know that content is work in progress.

### Difficulty
* Easy

**Comment by psk907** [comment]
I would like to work on this issue, can u assign it to me?

**Comment by tuladhar** [comment]
Sure @psk907. I've assigned it to you.

**Comment by psk907** [comment]
I have created a PR #7 to close this issue.
Thank you
